Homework 1
ok-technopolis-autumn-2022/Vladimir_Polshin pull request #1
Opened 2022-10-01 18:36 UTC by iampolshin

2022-10-03 07:52 UTC, fromanywhere requested changes
Неплохо. После сегодняшней лекции продолжим доработку в этом же PR

2022-10-03 07:52 UTC, fromanywhere commented on index.html
> +<html lang="">
нужно принять решение, каким языком будет пользоваться аудитория Вашего приложения

2022-10-03 08:14 UTC, iampolshin commented on index.html
> +<html lang="">
Исправлено. Выбрал английский, т.к. интерфейс приложения описан на нем, а использование, например, русского  языка нигде не обговаривалось, поэтому предположу, что ЦА англоязычная

2022-10-03 09:12 UTC, fromanywhere commented on index.html
> +<html lang="">
принимается

2022-10-10 09:16 UTC, fromanywhere approved these changes

2022-10-10 10:42 UTC, merged